Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StackOverflowClone.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StackOverflowClone.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

Pages/Create.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StackOverflowClone.Data;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using System.Linq;
using Microsoft.AspNetCore.Identity;

namespace StackOverflowClone.Pages
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CreateModel(ApplicationDbContext context, UserManager<ApplicationUser> userManager) {
            _context = context;
            _userManager = userManager;
        }
        
        public List<Tag> Tagslist { get; set; }
        public IActionResult OnGet()
        {

            Tagslist = _context.Tags.ToList();
            return Page();
        }
      

        [BindProperty]
        public Question Question { get; set; }
        [BindProperty]
        public int TagId { get; set; }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) 
            {
                return Page();
            }

            var user = await GetCurrentUser();
            user.Points += 5;
            Tag tag = _context.Tags.First(t =>t.Id == TagId);
            QuestionTag qt = new QuestionTag {
                QuestionId =Question.Id,
                Question = Question,
                TagId = tag.Id,
                Tag = tag

            };
            Question.QuestionTags.Add(qt);
            user.Questions.Add(Question);
            
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }

        private Task<ApplicationUser> GetCurrentUser() 
            => _userManager.GetUserAsync(HttpContext.User);        
    }
}

Pages/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StackOverflowClone.Data;

namespace StackOverflowClone.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DeleteModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Question Question { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Question = await _context.Questions
                .Include(p => p.Publisher).SingleOrDefaultAsync(m => m.Id == id);

            if (Question == null)
            {
                return NotFound();
            }

            if (Question.Publisher.UserName != User.Identity.Name)
            {
                return Redirect("../Index");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Question = await _context.Questions.FindAsync(id);

            if (Question != null)
            {
                _context.Questions.Remove(Question);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Details.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StackOverflowClone.Data;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using System.Linq;

namespace StackOverflowClone.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public DetailsModel(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public Question Question { get; private set; }

        [TempData]
        public int QuestionId { get; set; }
        [BindProperty]
        public Answer Answer { get; set; }
        [BindProperty]
        public Comment Comment { get; set; }
        
        public async Task<IActionResult> OnGetAsync(int? id) 
        {    
            if (id == null)
            {
                return NotFound();
            }

            Question = await _context.Questions
                .Include(q => q.Publisher)
                .Include(q => q.Answers)
                    .ThenInclude(a => a.Comments)
                .Include(c => c.Comments)
                    .ThenInclude(c => c.Question)
                .Include(c => c.Comments)
                    .ThenInclude(c => c.Publisher)
                .Include(p => p.QuestionTags)
                    .ThenInclude(pq => pq.Tag)
                .SingleOrDefaultAsync(m => m.Id == id);

            
            if (Question == null) 
            {
                return NotFound();
            }

            QuestionId = Question.Id;
            
            return Page();
        }

        public async Task<IActionResult> OnPostAnswerAsync()
        {
            if (!ModelState.IsValid)
            {
                return RedirectToPage("/Index");
            }

            Answer.Question = await GetQuestionAsync();
            var user = await GetUserAsync();
            user.Answers.Add(Answer);
            await _context.SaveChangesAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostCommentAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            
            Comment.Question = await GetQuestionAsync();
            var user = await GetUserAsync();
            user.Comments.Add(Comment);
            await _context.SaveChangesAsync();

            return Page();
        }

        private Task<Question> GetQuestionAsync() => _context.Questions.SingleOrDefaultAsync(q => q.Id == QuestionId);
        private Task<ApplicationUser> GetUserAsync() => _userManager.GetUserAsync(User);
    }
}

Pages/Edit.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StackOverflowClone.Data;
using Microsoft.AspNetCore.Identity;
using System.Linq;

namespace StackOverflowClone.Pages
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public EditModel(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [BindProperty]
        public Question Question { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id) 
        {
            if (id == null)
            {
                return NotFound();
            }

            Question = await _context.Questions
                .Include(q => q.Publisher).SingleOrDefaultAsync(q => q.Id == id);

            if (Question == null) 
            {
                return NotFound();
            }
            
            if (Question.Publisher.UserName != User.Identity.Name)
            {
                return Redirect("../Index");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            
            Question.Publisher = await _userManager.GetUserAsync(HttpContext.User);
            _context.Attach(Question).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!QuestionExists(Question.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool QuestionExists(int id)
        {
            return _context.Questions.Any(e => e.Id == id);
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StackOverflowClone.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using StackOverflowClone.Data;

namespace StackOverflowClone.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public IndexModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Question> Questions { get; private set; }

        public async Task<IActionResult> OnGetAsync(string state)
        {
            Questions = await _context.Questions
                .Include(q => q.Publisher)
                .AsNoTracking()
                .ToListAsync();
            
            if (state == null)
            {
                return Page();
            } 
            else if (Enum.TryParse(state, out State State))
            {
                Questions = Questions.Where(q => q.State == State).ToList();
                return Page();
            }
            else
            {
                return NotFound();                
            }
        }
    }
}

Pages/Leaderboard.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Linq;
using StackOverflowClone.Data;

namespace StackOverflowClone.Pages
{
    public class LeaderboardModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public LeaderboardModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Competitor> Users { get; private set; }

        public IActionResult OnGet()
        {
            Users = Leaderboard.Calculate(_context);

            return Page();
        }
    }
}

Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Pages/Create.cshtml
@page
@model CreateModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Question</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Question.Title" class="control-label"></label>
                <input asp-for="Question.Title" class="form-control" />
                <span asp-validation-for="Question.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Question.Body" class="control-label"></label>
                <input asp-for="Question.Body" class="form-control" />
                <span asp-validation-for="Question.Body" class="text-danger"></span>
            </div>
            <select asp-for="TagId"
                asp-items="@(new SelectList(Model.Tagslist, "Id", "Name"))">

            </select>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Delete.cshtml
@page "{id:int?}"
@model DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Question.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Question.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Question.Body)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Question.Body)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Question.Publisher)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Question.Publisher.Id)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Question.Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Details.cshtml
@page "{id:int?}"
@model DetailsModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Question Details";
}

<h2>@ViewData["Title"]</h2>

<div>
    <h4>Question</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Question.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Question.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Question.Body)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Question.Body)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Question.Publisher)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Question.Publisher.UserName)
        </dd>
    </dl>
    
    <div>
        @if (SignInManager.IsSignedIn(User))
        {
            <a class="btn btn-default">Upvote</a>
            <a class="btn btn-default">Downvote</a>
        }

        @if (SignInManager.IsSignedIn(User) && UserManager.GetUserId(User).Equals(Model.Question.Publisher.Id))
        {
            <a class="btn btn-default" asp-page="./Edit" asp-route-id="@Model.Question.Id">Edit</a>
        }
        
        <a class="btn btn-default" asp-page="./Index">Back to List</a>
        
        @if (SignInManager.IsSignedIn(User) && UserManager.GetUserId(User).Equals(Model.Question.Publisher.Id)
                                            && Model.Question.State.Equals(State.Open))
        {
            <a class="btn btn-default">Close question</a>
        }
        else if (SignInManager.IsSignedIn(User) && UserManager.GetUserId(User).Equals(Model.Question.Publisher.Id) && Model.Question.State.Equals(State.Closed))
        {
            <a class="btn btn-default">Open question</a>
        }
    </div>
    <hr />

    <h5 class="badge badge-secondary">Tags</h5>
    <div>
        @foreach(var item in @Model.Question.QuestionTags)
        {
            <a asp-page="/Tags/Index" asp-route-name="@item.Tag.Name" class="btn btn-primary">@item.Tag.Name</a>
        }
    </div>
    <hr />

    <h5 class="badge badge-secondary">Answers</h5>
    <div>
        <ul>
            @foreach (var contact in Model.Question.Answers)
            {
                <li>@contact.Vote vote: @contact.Body</li>
            }
        </ul>
    </div>
    @if (SignInManager.IsSignedIn(User))
    {    
    <div class="row">
        <div class="col-md-4">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Answer.Body" class="control-label"></label>
                    <input asp-for="Answer.Body" class="form-control" />
                    <span asp-validation-for="Answer.Body" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" asp-page-handler="answer" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>
    }
    <hr />

    <h5 class="badge badge-secondary">Comments</h5>
    <div class="comments">
        <ul class="list-group">
            @foreach (var comment in @Model.Question.Comments)
            {
                <li class="list-group-item">
                    <em>@comment.Publisher.UserName</em>
                    &nbspcommented:

                    @comment.Body
                </li>
            }
        </ul>
    </div>

    @if (SignInManager.IsSignedIn(User))
    {
    <div class="card">
        <div class="card-block">
            <form method="POST">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Comment.Id" />     
                <div class="form-group">
                    <textarea name="body" asp-for="Comment.Body" placeholder="Your comment here." class="form-control" required></textarea>
                </div>
                <div class="form-group">
                    <input type="submit" asp-page-handler="comment" value="Add comment" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>
    }
</div>

Pages/Edit.cshtml
@page "{id:int?}"
@model EditModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Question</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Question.Id" />
            <div class="form-group">
                <label asp-for="Question.Title" class="control-label"></label>
                <input asp-for="Question.Title" class="form-control" />
                <span asp-validation-for="Question.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Question.Body" class="control-label"></label>
                <input asp-for="Question.Body" class="form-control" />
                <span asp-validation-for="Question.Body" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Index.cshtml
@page
@model IndexModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Index";
}

<div class="content">
    <div class="inner_content">
        <h3>Search through Open/Closed questions</h3>
        <a asp-page="/Index" asp-route-state="Open"><button class="go_button">Open</button></a>
        <a asp-page="/Index" asp-route-state="Closed"><button class="go_button">Closed</button></a>
        <h3> Or </h3>
        <form method="post">
            @if (SignInManager.IsSignedIn(User))
            {
                <div class="button">
                    <a class="askbutton" asp-page="./Create">Ask a question yourself</a>
                </div>
            }
            @if (!SignInManager.IsSignedIn(User))
            {
                <div class="button">
                    <a class="askbutton" asp-page="Create" title="You have to be logged in to ask questions">Ask a question yourself</a>
                </div>
            }
        </form>
    </div>
    <div class="questions">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Title
                    </th>
                    <th>
                        Body
                    </th>
                    <th>
                        Publisher
                    </th>
                    <th>
                        State
                    </th>
                    <th>
                        Votes
                    </th>
                    <th>
                        Answers
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Questions)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Body)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Publisher.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.State)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Vote)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Answers.Count)
                    </td>
                    <td>
                        <a class="btn btn-default" asp-page="./Details" asp-route-id="@item.Id">Details</a>
                        @if (SignInManager.IsSignedIn(User) && UserManager.GetUserId(User).Equals(item.Publisher.Id))
        {
                @: |
                <a class="btn btn-default" asp-page="./Edit" asp-route-id="@item.Id">Edit</a>
                @: |
                <a class="btn btn-default" asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
}
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Pages/Leaderboard.cshtml
@page
@model LeaderboardModel
@{
    ViewData["Title"] = "Leaderboard";
}

<h4>@ViewData["Title"]</h4>

<div class="row">
    <div class="col-md-6">
        <table class="table">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Points</th>
                    <th>Username</th>
                </tr>
            </thead>
            <tbody>
                @{int i = 1;}
                @foreach (var item in Model.Users)
                {
                    <tr>
                        <td>@i @{i++;}</td>
                        <td>@item.Points</td>
                        <td>@item.Name</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StackOverflowClone</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">StackOverflowClone</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Leaderboard">Leaderboard</a></li>
                    <li><a asp-page="/Tags/Index">Tags</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <img id="logo" src="https://i.imgur.com/SSDhOrD.png">
        <div class="wrapper">
            @RenderBody()
        </div>
        <div class="push"></div>
        <footer class="footer">
            <p>&copy; 2018 - StackOverflowClone</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>